# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Canonical Ltd.
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    labels:
      - dependencies
    target-branch: "main"