# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Canonical Ltd.
name: Hadolint

on:
  workflow_call:
    inputs:
      branch-name:
        description: Name of the branch to checkout
        required: false
        type: string
        default: ${{ github.ref }}


jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Dockerfile linter
        uses: hadolint/hadolint-action@v3.1.0
        # Ignoring:
        # DL3008 warning: Pin versions in apt get install (e.g., apt-get install <package>=<version>); and
        # DL3018 warning: Pin versions in apk add (e.g., apk add <package>=<version>)
        with:
          dockerfile: Dockerfile
          ignore: DL3008,DL3018
