# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Canonical Ltd.
name: License Check

on:
  workflow_call:
    inputs:
      branch-name:
        description: Name of the branch to checkout
        required: false
        type: string
        default: ${{ github.ref }}
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}

      - name: reuse lint
        uses: fsfe/reuse-action@v5
