# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Canonical Ltd.
name: Push Images

on:
  workflow_call:
    inputs:
      branch-name:
        description: Name of the branch to checkout
        required: false
        type: string
        default: ${{ github.ref_name }}

jobs:
  push-images:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'omec-project'
    env:
      REGISTRY: registry.aetherproject.org
      DOCKER_REGISTRY: registry.aetherproject.org/
      DOCKER_REPOSITORY: sdcore/
      BRANCH_NAME: ${{ inputs.branch-name }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - run: echo GIT_SHA_SHORT=$(git rev-parse --short HEAD) >> $GITHUB_ENV

      - uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.AETHER_REGISTRY_USERNAME }}
          password: ${{ secrets.AETHER_REGISTRY_PASSWORD }}

      - name: Build and push "${{ env.BRANCH_NAME }}-latest" Docker image
        env:
          DOCKER_TAG: ${{ env.BRANCH_NAME }}-latest
        run: |
          make docker-build
          make docker-push

      - name: Build and push "${{ env.BRANCH_NAME }}-GIT_SHA" Docker image
        env:
          DOCKER_TAG: ${{ env.BRANCH_NAME }}-${{ env.GIT_SHA_SHORT }}
        run: |
          make docker-build
          make docker-push
