# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Canonical Ltd.
name: Release Docker Image

on:
  workflow_run:
    workflows: ["Tag GitHub"]
    types:
      - completed

jobs:
  release-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      REGISTRY: docker.io
      DOCKER_REGISTRY: docker.io/
      DOCKER_REPOSITORY: omecproject/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push release Docker image
        env:
          DOCKER_TAG: rel-${{ github.event.workflow_run.outputs.version }}
        run: |
          make docker-build
          make docker-push
