# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Canonical Ltd.
name: Update Version

on:
  workflow_run:
    workflows: ["Tag GitHub"]
    types:
      - completed

jobs:
  update-version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Increment version
        run: |
          version=${{ github.event.workflow_run.outputs.version }}
          IFS='.' read -r major minor patch <<< "$version"
          patch_update=$((patch+1))
          NEW_VERSION="$major.$minor.$patch_update-dev"
          echo $NEW_VERSION > VERSION
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add VERSION && git commit -m "Update VERSION file to $NEW_VERSION" && git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_OMEC_PAT }}
          commit-message: Update version
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: version-update
          delete-branch: true
          title: Update version
          body: |
            Update VERSION file
          add-paths: |
            VERSION