# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Canonical Ltd.
name: Branch Release

on:
  workflow_run:
    workflows:
      - "Tag GitHub"
    types:
      - completed

jobs:
  branch-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.outputs.release_branch == 'true' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GH_OMEC_PAT }}
    steps:
      - uses: actions/checkout@v4

      - uses: peterjgrainger/action-create-branch@v3.0.0
        with:
          branch: "rel-${{ github.event.workflow_run.outputs.version_branch }}"
