# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Canonical Ltd.
name: Release Image

on:
  workflow_run:
    workflows:
      - "Tag GitHub"
    types:
      - completed

  workflow_call:
    inputs:
      aether_registry:
        description: "Aether Registry URL"
        default: "registry.aetherproject.org"
        type: string
      aether_repository_namespace:
        description: "Namespace for Aether repository"
        default: "omecproject"
        type: string
      docker_registry:
        description: "Docker Registry URL"
        default: "docker.io"
        type: string
      docker_repository_namespace:
        description: "Namespace for Docker repository"
        default: "sdcore"
        type: string
      branch_name:
        description: "Name of the branch to checkout"
        required: false
        type: string
        default: "main"
      repository_name:
        description: "Name of the repository"
        type: string
        required: true

jobs:
  release-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      DOCKER_IMAGE_NAME: ${{ inputs.docker_repository_namespace}}/${{ inputs.repository_name }}
      AETHER_IMAGE_NAME: ${{ inputs.aether_repository_namespace}}/${{ inputs.repository_name }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ inputs.docker_registry }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.workflow_run.outputs.version }} .

      - name: Push to Docker Hub
        run: |
          docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.workflow_run.outputs.version }}

      - name: Login to Aether registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ inputs.aether_registry }}
          username: ${{ secrets.AETHER_USERNAME }}
          password: ${{ secrets.AETHER_PASSWORD }}

      - name: Push to Aether registry
        run: |
          docker tag ${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.workflow_run.outputs.version }}  ${{ env.AETHER_IMAGE_NAME }}:${{ github.event.workflow_run.outputs.version }}
          docker push ${{ env.AETHER_IMAGE_NAME }}:${{ github.event.workflow_run.outputs.version }}
